### ISSUE TITLE
adam doesn't know how to download all the stuff to a local machine

### ISSUE THREAD

**Issue by adamborecki** [aarongrisez/GPyUpload#10]
i'm submitting this as a test issue

i'm trying to learn how to download all the files locally

i already have git installed via brew install get

i just ran brew upgrade git

i'm going to try some stuff... maybe a pull request will work...?

**Comment by aarongrisez** [comment]
Command you're looking for is

```bash
git clone git@github.com:aarongrisez/GPyUpload.git
```

Pull requests would be used if you branched off of Master, made some changes, and wanted to merge them into Master.

We're also going to work off of the private repo for our test this semester.
